name: ElixirXDR CD

on:
  release:
    types:
      [published]

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  publish:
    name: Publish Release to HEX PM
    runs-on: ubuntu-20.04
    strategy:
       matrix:
        otp: ['22.3']
        elixir: ['1.11']
    env:
      HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            github.com:443
            hex.pm:443
            repo.hex.pm:443
            builds.hex.pm:443

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: erlef/setup-beam@5304e04ea2b355f03681464e683d92e3b2f18451 # v1.18.2
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}
      - uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4.1.2
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-mix-
      - name: Install Dependencies
        run: |
          rm -rf deps _build
          mix deps.get
      - name: Publish
        run: HEX_API_KEY=$HEX_API_KEY mix hex.publish --yes
