name: ElixirXDR CD

on:
  release:
    types:
      [published]

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  publish:
    name: Publish Release to HEX PM
    runs-on: ubuntu-20.04
    strategy:
       matrix:
        otp: ['22.3']
        elixir: ['1.11']
    env:
      HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            github.com:443
            hex.pm:443
            repo.hex.pm:443
            builds.hex.pm:443

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: erlef/setup-beam@54075bcc5e249e4758d363f27d099f55d843f124 # v1.24.1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}
      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-mix-
      - name: Install Dependencies
        run: |
          rm -rf deps _build
          mix deps.get
      - name: Publish
        run: HEX_API_KEY=$HEX_API_KEY mix hex.publish --yes
